export function generateZshCompletion(): string {
  return `#compdef multi-claude
# shellcheck shell=zsh
# Generated by: multi-claude completion zsh
# Add to fpath: cp this file to /usr/local/share/zsh/site-functions/_multi-claude
#   or append to ~/.zshrc: source <(multi-claude completion zsh)

_multi_claude() {
  local curcontext=\$curcontext state state_descr line
  typeset -A opt_args

  local -a commands
  commands=(
    'start:Start a new Claude Code session in a tmux window'
    'stop:Stop a running session'
    'list:List all managed sessions'
    'attach:Attach to the tmux session'
    'config:Show or update session configuration'
    'restart:Restart a session'
    'rename:Rename a session'
    'duplicate:Clone a session configuration'
    'kill-all:Stop all sessions and kill the tmux session'
    'models:List common model aliases'
    'logs:Show recent output from a session'
    'completion:Generate shell completion script'
  )

  local -a session_names
  session_names=(\\\${(f)\\"\\$(node -e "try{const s=require(\\'os\\').homedir()+\\'/.multi-claude/sessions.json\\';const d=require(\\'fs\\').readFileSync(s,\\'utf8\\');const j=JSON.parse(d);console.log(Object.keys(j.sessions||{}).join(\\'\\\\n\\'));}catch(e){}" 2>/dev/null)\\"})

  _arguments -C \\
    '1: :->command' \\
    '*:: :->args'

  case \\\$state in
    command)
      _describe 'command' commands
      ;;
    args)
      case \\\$words[1] in
        start)
          _arguments \\
            '-m[LLM model]:model:()' \\
            '--model[LLM model]:model:()' \\
            '-d[Working directory]:dir:_directories' \\
            '--dir[Working directory]:dir:_directories' \\
            '--desc[Session description]' \\
            '-s[Custom system prompt]' \\
            '--system-prompt[Custom system prompt]' \\
            '-p[Permission mode]:mode:(default acceptEdits plan bypassPermissions)' \\
            '--permission-mode[Permission mode]:mode:(default acceptEdits plan bypassPermissions)' \\
            '-e[Effort level]:level:(low medium high xhigh max)' \\
            '--effort[Effort level]:level:(low medium high xhigh max)' \\
            '--settings[Settings file]:file:_files' \\
            '--mcp-config[MCP config files]:file:_files' \\
            '--extra-args[Extra arguments]' \\
            '-f[Force restart]' \\
            '--force[Force restart]' \\
            '--all[Start all stopped sessions]' \\
            '1: :->session_names'
          ;;
        stop)
          _arguments \\
            '--remove[Also remove from managed list]' \\
            '--all[Stop all sessions]' \\
            '1:session:->session_names'
          ;;
        attach|config|restart|rename|duplicate|logs)
          _arguments '1:session:->session_names'
          ;;
      esac
      ;;
    session_names)
      if [[ -n \\\${session_names} ]]; then
        _describe 'session' session_names
      fi
      ;;
  esac
}

_multi_claude "\$@"
`;
}

export function generateBashCompletion(): string {
  return `# shellcheck shell=bash
# Generated by: multi-claude completion bash
# Source in ~/.bashrc: source <(multi-claude completion bash)

_multi_claude_completion() {
  local cur prev words cword
  _init_completion || return

  local opts="start stop list attach config restart rename duplicate kill-all models logs completion"
  local sessions
  sessions=\\$(node -e "try{const s=require('os').homedir()+'/.multi-claude/sessions.json';const d=require('fs').readFileSync(s,'utf8');const j=JSON.parse(d);console.log(Object.keys(j.sessions||{}).join(' '));}catch(e){}" 2>/dev/null)

  case \\\${prev} in
    start)
      if [[ \\\${cur} == -* ]]; then
        COMPREPLY=( \\$(compgen -W "-m --model -d --dir --desc -s --system-prompt -p --permission-mode -e --effort --settings --mcp-config --extra-args -f --force --all" -- "\\\${cur}") )
      else
        COMPREPLY=( \\$(compgen -W "\\\${sessions}" -- "\\\${cur}") )
      fi
      return 0
      ;;
    stop|attach|config|restart|rename|duplicate|logs)
      COMPREPLY=( \\$(compgen -W "\\\${sessions}" -- "\\\${cur}") )
      return 0
      ;;
    stop)
      if [[ \\\${cur} == -* ]]; then
        COMPREPLY=( \\$(compgen -W "--remove --all" -- "\\\${cur}") )
      else
        COMPREPLY=( \\$(compgen -W "\\\${sessions}" -- "\\\${cur}") )
      fi
      return 0
      ;;
    -m|--model|-d|--dir|-p|--permission-mode|-e|--effort|--settings|--mcp-config)
      return 0
      ;;
  esac

  COMPREPLY=( \\$(compgen -W "\\\${opts}" -- "\\\${cur}") )
  return 0
}

complete -F _multi_claude_completion multi-claude
`;
}
